### PR TITLE
Work done for #40 to add featured team members panel to home page

### PR DESCRIPTION
**Pull request by zacharysang**
* Added StatsBlock component to display statistic figure and name
* Pre-loaded src/views/FeaturedTeamPanel/FeaturedTeamData.js with statistics and images of our fearless leader, Kiera Peltz
* Added src/views/FeaturedTeamPanel component for all this work

### CODE REVIEW

**Comment by zacharysang** [comment]
Reference #40

**Comment by bibekg** [comment]
Can you add this component to the home page below the "Updates" section?

**Comment by zacharysang** [comment]
I put the component under updates as you asked and also noticed some of my changes didn't make it into the last commit so I added those too. It should all be there now

**Comment by bibekg** [comment]
There's some excess padding around images that make it not match the mockup.
Also, the button is overflowing out of the div.

image

**Comment by zacharysang** [comment]
Yeah, the padding around the images is because the MemberImage component is hardcoded to be 250px ($member_image_size is defined in Variables.scss) when this is combined with our flexbox rule to justify-content: space-around, means that there will be some whitespace filling the gaps. I can fix this, but would need to update how the MemberImage is defined as right now it's size cannot be intuitively stretched/ resized.

Do you know if there is there a reason for this static sizing that I would mess up by changing this?

**Comment by bibekg** [comment]
Hm, good catch. I think that's bad CSS on my part. The `MemberImage` component should make no claims about its own size; that should be up to its container to decide. Let's do this:
1. Remove all hardcoded sizing constraints in `MemberImage`.
2. Add children sizing constraints to the some appropriate container of `MemberImage` on the team page, e.g. `TeamSection`
3. Add children sizing constraints to `FeaturedTeamMembers`

**Comment by zacharysang** [comment]
For posterity, here is the list of team members pasted from Slack:
* Lauren Becker (for sure)
* Zachary Sang   (for sure)
* Kathy Nguyen (if you need a closer up of Kathy, let her know),  (for sure)
* Ati Ok,  (for sure)
* Anna Cosentino  
* James Szabo
* Lian Showl 
* KJ Famulegun (if you can make her photo closer up)
* Junius Murphy (if photo is close enough up)

> Note: If any of the above don't work, use Annie Luc next

It looks like this is related to #33 as most of these images are included here. I will start work on this: For this merge request I will simply upload all image files so we have them available. Afterwards, I will make a separate merge request for #33 that includes these new members on the 'Our Team' page. How does that sound @bibekg ?

**Review by bibekg — CHANGES_REQUESTED** [review]
Featured team panel looks great, but Kiera's image is missing on the team page

**Comment by zacharysang** [comment]
@bibekg The problem was just that with the new MemberImage rules to fit the container, the image collapsed to have 0 width. This change added a wrapper around the MemberImage element in the MemberCard component with a fixed height and width of 250px.

**Review by bibekg — APPROVED** [review]

**Pull request merged**
