### PR TITLE
IS-17 - Redesigned Updates Feed

### PR DESCRIPTION
**Pull request by bibekg**
**Demo:**
ezgif com-video-to-gif 1

### CODE REVIEW

**Comment by crayolakat** [comment]
The Updates Feed does not display right in Internet Explorer and Microsoft Edge.

Internet Explorer:
internet_explorer_1
internet_explorer_2

Microsoft Edge:
microsoft_edge_1
microsoft_edge_2

**Comment by bibekg** [comment]
Ah, of course. Leave it to IE and Edge to always make web-dev harder than it needs to be.

**Comment by bibekg** [comment]
Okay, fairly certain I've fixed the Edge/IE bugs now.

**Comment by crayolakat** [comment]
Now the updates overlap in Internet Explorer
screenshot 14

**Comment by bibekg** [comment]
@crayolakat Looks fine on IE 11 when I test it... Looks like you may have some strange combination of the old and new updates. In the new version (on this PR), I no longer have the video for that "On TV" update that's huge on your screenshot.
image

**Pull request merged**
